### ISSUE TITLE
Conda installation

### ISSUE THREAD

**Issue by rivera10** [DecodeGenetics/Ratatosk#27]
Hello,

Great tool! Would it be possible to have a Bioconda recipe for Ratatosk? This way it will also trigger the creation of Biocontainers (docker and singularity) that can be integrated in assembly pipelines. Thanks

Best,
Ramon

**Comment by GuillaumeHolley** [comment]
Hi @rivera10,

I am not very familiar with bioconda in general (I only did one bioconda recipe so far) but I can surely come up with something :) I'll keep the issue open while it is in progress and will let you know here as soon as it is ready.

Guillaume

**Comment by rivera10** [comment]
Hello @GuillaumeHolley,

Thanks for the fast answer. For bioconda here is basically what you need. 

1- Folk repository
2- Create a directory for `ratatosk` under the recipes directory (i.e. `bioconda-recipes/recipes/ratatosk`)
3- Create file `meta.yaml` (i.e. `bioconda-recipes/recipes/ratatosk/meta.yaml`)
For ratatosk will be like this
```
{% set name = 'Ratatosk' %}
{% set version = '0.1' %}

package:
  name: {{ name }}
  version: {{ version }}

build:
  number: 0

source:
  url: https://github.com/DecodeGenetics/Ratatosk/archive/{{ version }}.tar.gz
  sha256: 9b82c6875e3613b12ecdc264eaa7c920da5c7ba7256e95ab5528dbdb65e4cc90

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - cmake
  host:
    - zlib
  run:
    - zlib

test:
  commands:
    - Ratatosk --help

about:
  home: https://github.com/DecodeGenetics/Ratatosk
  license: BSD-2-Clause
  license_file: LICENSE
  summary: "Ratatosk is a phased error correction tool for erroneous long reads based on compacted and colored de Bruijn graphs built from accurate short reads."

```

4- Create file `build.sh` (i.e. `bioconda-recipes/recipes/ratatosk/build.sh`)

5- Create a PR to the `bioconda:master` and follow the instructions they give in the PR page. 

Hope this can help.

Ramon
